version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1
  slack: circleci/slack@4.10.1

jobs:
  install:
    working_directory: ~/symeo-js
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-js/yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - checkout # Checking out code in case of a yarn version mismatch modifies the yarn.lock
      - save_cache:
          key: dependency-cache-{{ checksum "~/symeo-js/yarn.lock" }}
          paths:
            - node_modules
      - slack/notify:
          event: fail
          template: basic_fail_1
  lint:
    working_directory: ~/symeo-js
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-js/yarn.lock" }}
      - run:
          name: Lint
          command: yarn lint
      - slack/notify:
          event: fail
          template: basic_fail_1
  build:
    working_directory: ~/symeo-js
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-js/yarn.lock" }}
      - run:
          name: Build
          command: yarn build
      - slack/notify:
          event: fail
          template: basic_fail_1
  test:
    working_directory: ~/symeo-js
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-js/yarn.lock" }}
      - run:
          name: Test
          command: yarn test
      - slack/notify:
          event: fail
          template: basic_fail_1
  publish:
    working_directory: ~/symeo-js
    docker:
      - image: cimg/node:16.16.0
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "~/symeo-js/yarn.lock" }}
      - run:
          name: Build
          command: yarn build
      - run:
          name: Authenticate to registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/symeo-js/.npmrc
      - run:
          name: Publish
          command: npm publish
      - slack/notify:
          event: fail
          template: basic_fail_1

workflows:
  package:
    jobs:
      - install:
          context:
            - slack-notifications
      - test:
          requires:
            - install
          context:
            - slack-notifications
      - lint:
          requires:
            - install
          context:
            - slack-notifications
      - build:
          requires:
            - install
          context:
            - slack-notifications
      - publish:
          requires:
            - lint
            - test
            - build
          context:
            - slack-notifications
            - npm
          filters:
            branches:
              only:
                - main
