export const LOCAL_VALUES_FILE_VARIABLE_NAME = 'SYMEO_LOCAL_VALUES_FILE';
export const CONTRACT_FILE_VARIABLE_NAME = 'SYMEO_CONTRACT_FILE';
export const API_URL_VARIABLE_NAME = 'SYMEO_API_URL';
export const API_KEY_VARIABLE_NAME = 'SYMEO_API_KEY';
